dist: xenial
language: go
env:
- GO111MODULE=on
go:
- 1.12.x
git:
  depth: 1
install: true
before_script:
- go install github.com/golangci/golangci-lint/cmd/golangci-lint
- go install github.com/mitchellh/gox
script:
- make fmt check build-cross
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rK2BUQrIAGIMvwqN0NPajL2umlgchXhATQJuyZkMYpMYAEcN0gIoAV/MNReOfAr3jzwNqpcof6dnsLib0ajZIGC/hU4l1QZaDpIeY8ElJ8pnzN5tgIMen/uNEv7ajqi7B+fIQ6KybxVHZmVPl3BlIliQTu1PJsT8lXk7E9+XtOY/xfvvmb6jZYGEs6x85MtYB/xG1ggpG8gMY8U/WbZ9ikOZ0+dq+VFs/gqEtZFX2tgVkjsN511b6m4hcmSc9UGJfR0pGJXFWRoi4LZxCLCohRP+htJgk/xjjxZ90CY8skKc8toZk6uXIKOynmR2GuIgU3l4yh5uuSKtdF+5sUwTZv/5tWC0SSt4qTQ8tfdkkioTRJ2m/0YWrRASycS7jAacRVyclGHs0ZyDTxO0PHD83eF7cageabDKJWOMo2iR3YArDWiLq8BGf7M1C+c3gDNsuS7R+93valVDog1E9HtfRw8RsHxulIc81poGZLmV1pweVgE+A0UlrSz+Ex2qXyUdnJX5PEH0rFXb9RhkGoc4CnZ8uJApQCOsTlkdshAm2O01NOBmRdBb+QwdVUKUaTZEszeyrU9f8Ip/VCOagmUcqxo7Xxng+/l2FmVhXe1HlDJwK0AKY8dEYkGBlb9f7J9ahd2Bp3ghDwmEQCUprucmITw8f6zrYhQoQSUv/0FUW7Y=
  file:
  - _dist/k3d-darwin-amd64
  - _dist/k3d-linux-386
  - _dist/k3d-linux-amd64
  - _dist/k3d-linux-arm
  - _dist/k3d-linux-arm64
  - _dist/k3d-windows-amd64.exe
  on:
    repo: zeerorg/k3s-in-docker
    tags: true